"""Generate 16px bitmap font C header from Windows TTF."""
import os, sys
from PIL import Image, ImageDraw, ImageFont

GLYPH_W, GLYPH_H = 16, 16

def find_font():
    for p in ['C:/Windows/Fonts/consola.ttf', 'C:/Windows/Fonts/lucon.ttf',
              'C:/Windows/Fonts/cour.ttf']:
        if os.path.exists(p):
            return p
    return None

def generate(out_path):
    fpath = find_font()
    if not fpath:
        print("No monospace font found", file=sys.stderr)
        sys.exit(1)
    font = ImageFont.truetype(fpath, 14)  # 14pt for 16px cap height

    chars = [chr(i) for i in range(32, 127)]
    glyphs = {}
    max_h = 0
    for c in chars:
        bbox = font.getbbox(c)
        h = bbox[3] - bbox[1]
        if h > max_h: max_h = h

    byte_w = GLYPH_W // 8

    with open(out_path, 'w') as f:
        f.write(f'// Auto-generated by {os.path.basename(__file__)}\n')
        f.write(f'// Font: {os.path.basename(fpath)}, {GLYPH_W}x{GLYPH_H}px\n')
        f.write(f'// ASCII 32-126 (95 glyphs)\n\n')
        f.write('#pragma once\n')
        f.write('#include <stdint.h>\n\n')
        f.write(f'#define FONT_W  {GLYPH_W}\n')
        f.write(f'#define FONT_H  {GLYPH_H}\n')
        f.write(f'#define FONT_BPW {byte_w}\n\n')
        f.write(f'static const uint8_t font_data[{len(chars)}][{GLYPH_H * byte_w}] = {{\n')

        for c in chars:
            img = Image.new('L', (GLYPH_W, GLYPH_H), 0)
            draw = ImageDraw.Draw(img)
            bbox = font.getbbox(c)
            x = (GLYPH_W - (bbox[2] - bbox[0])) // 2 - bbox[0]
            y = (GLYPH_H - max_h) // 2 + (max_h - (bbox[3] - bbox[1])) // 2 - bbox[1]
            draw.text((x, y), c, fill=255, font=font)
            rows = []
            for row in range(GLYPH_H):
                for b in range(byte_w):
                    byte = 0
                    for bit in range(8):
                        col = b * 8 + bit
                        if img.getpixel((col, row)) > 128:
                            byte |= (1 << (7 - bit))
                    rows.append(byte)
            hex_vals = ', '.join(f'0x{b:02X}' for b in rows)
            f.write(f'    {{ {hex_vals} }},  // {c!r}\n')

        f.write('};\n')
    print(f'Written: {out_path} ({len(chars)} glyphs)')

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(f'Usage: {sys.argv[0]} <output.h>')
        sys.exit(1)
    generate(sys.argv[1])
